### ISSUE TITLE
Problems with VCARD 2.1 from Outlook

### ISSUE THREAD

**Issue by escoand** [NWiBGRsK/vcard#1]
In my VCARD files from OUTLOOK I've some entries with "TEL;PAGER;VOICE". They are not supported by the script or VCARD 4.0.
```
ERROR could no add this line 'TEL;PAGER;VOICE:...' to VCard object
did not recognize this value 'PAGER'
Traceback (most recent call last):
  File "vcard.py", line 728, in <module>
  File "vcard.py", line 297, in fromFile
  File "vcard.py", line 278, in fromString
  File "vcard.py", line 265, in fromString
  File "vcard.py", line 521, in setTEL
  File "vcard.py", line 156, in getKeyAndValueQualifiersAsDict
ValueError: did not recognize this value 'PAGER'
[17288] Failed to execute script vcard
```

**Comment by NWiBGRsK** [comment]
Thanks for pointing this out. Should now work.

**Comment by escoand** [comment]
Thanks for the fast fix. Now all my files are working...
